### ISSUE TITLE
Attempted to get default timeout for nccl backend, but NCCL support is not compiled

### ISSUE THREAD

**Issue by AdamMiltonBarker** [meta-llama/llama3#153]
Machine: Standard NC96ads A100 v4 (96 vcpus, 880 GiB memory) 

```
 torchrun --nproc_per_node 1 example_chat_completion.py \
>     --ckpt_dir Meta-Llama-3-8B-Instruct/ \
>     --tokenizer_path Meta-Llama-3-8B-Instruct/tokenizer.model \
>     --max_seq_len 512 --max_batch_size 6
/home/tmsisa/.conda/envs/llama_3_pytorch_env/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py:613: UserWarning: Attempted to get default timeout for nccl backend, but NCCL support is not compiled
  warnings.warn("Attempted to get default timeout for nccl backend, but NCCL support is not compiled")
Traceback (most recent call last):
  File "/home/tmsisa/llama3/example_chat_completion.py", line 84, in <module>
    fire.Fire(main)
  File "/home/tmsisa/.conda/envs/llama_3_pytorch_env/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tmsisa/.conda/envs/llama_3_pytorch_env/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/tmsisa/.conda/envs/llama_3_pytorch_env/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tmsisa/llama3/example_chat_completion.py", line 31, in main
    generator = Llama.build(
                ^^^^^^^^^^^^
  File "/home/tmsisa/llama3/llama/generation.py", line 68, in build
    torch.distributed.init_process_group("nccl")
  File "/home/tmsisa/.conda/envs/llama_3_pytorch_env/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tmsisa/.conda/envs/llama_3_pytorch_env/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 89, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tmsisa/.conda/envs/llama_3_pytorch_env/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 1312, in init_process_group
    default_pg, _ = _new_process_group_helper(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tmsisa/.conda/envs/llama_3_pytorch_env/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 1513, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL built in")
RuntimeError: Distributed package doesn't have NCCL built in
E0426 08:51:39.962000 140532787892608 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 51564) of binary: /home/tmsisa/.conda/envs/llama_3_pytorch_env/bin/python
Traceback (most recent call last):
  File "/home/tmsisa/.conda/envs/llama_3_pytorch_env/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.3.0', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tmsisa/.conda/envs/llama_3_pytorch_env/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/tmsisa/.conda/envs/llama_3_pytorch_env/lib/python3.12/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/home/tmsisa/.conda/envs/llama_3_pytorch_env/lib/python3.12/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/tmsisa/.conda/envs/llama_3_pytorch_env/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tmsisa/.conda/envs/llama_3_pytorch_env/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-26_08:51:39
  host      : tmsisa.internal.cloudapp.net
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 51564)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

**Comment by AdamMiltonBarker** [comment]
OK it looks like it had reverted to CPU installation of PyTorch somehow, attempting GPU installation again,

**Comment by AdamMiltonBarker** [comment]
This was resolved by reinstalling PyTorch

**Comment by rain7996** [comment]
Do you have a GPU to run it? What if I run it on a CPU-only machine? I install the pytorch CPU version but have the same error with you. How should I deal with it? Thanks a lot!
